---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: nginx-source
  targetNamespace: default
  timeout: 1m0s
  wait: true
